// <auto-generated />
using System;
using FamilyTreeAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.EntityFrameworkCore.Sqlite;


namespace FamilyTreeAPI.Migrations
{
    [DbContext(typeof(FamilyTreeContext))]
    [Migration("20231024142942_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("FamilyTreeAPI.Marriage", b =>
                {
                    b.Property<int>("MarriageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EndYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Person1ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Person2ID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("MarriageID");

                    b.ToTable("Marriages");
                });

            modelBuilder.Entity("FamilyTreeAPI.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfDeath")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaidenName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Parent1ID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Parent2ID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YearOfBirth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YearOfDeath")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonID");

                    b.ToTable("People");
                });
#pragma warning restore 612, 618
        }
    }
}
